#!/bin/bash
# IntercomBounty Demo Script - Complete Workflow
# This script demonstrates the full bounty lifecycle

echo "============================================"
echo "  IntercomBounty - Complete Demo Workflow"
echo "============================================"
echo ""
echo "This demo will walk through:"
echo "1. Posting a bounty"
echo "2. Claiming a bounty"
echo "3. Submitting work"
echo "4. Approving work"
echo ""
echo "Prerequisites:"
echo "- Two terminals open"
echo "- Admin peer running in Terminal 1"
echo "- Worker peer running in Terminal 2"
echo ""
read -p "Press Enter when both peers are ready..."

echo ""
echo "============================================"
echo "STEP 1: Post a Bounty (Run in Terminal 1)"
echo "============================================"
echo ""
echo "Copy and paste this command in Terminal 1 (Poster):"
echo ""
echo '/bounty_post --title "Build Simple Calculator" --desc "Create a JavaScript calculator with basic operations (+, -, *, /)" --reward "5000000000000000000"'
echo ""
echo "This will generate a TX command. Copy that command and run it."
echo ""
read -p "Press Enter after you've posted the bounty..."

echo ""
echo "============================================"
echo "STEP 2: View Available Bounties (Terminal 2)"
echo "============================================"
echo ""
echo "Copy and paste this command in Terminal 2 (Worker):"
echo ""
echo '/tx --command "list_bounties"'
echo ""
echo "You should see bounty_1 with status 'open'"
echo ""
read -p "Press Enter after viewing bounties..."

echo ""
echo "============================================"
echo "STEP 3: Claim the Bounty (Terminal 2)"
echo "============================================"
echo ""
echo "Copy and paste in Terminal 2 (Worker):"
echo ""
echo '/bounty_claim --id "bounty_1"'
echo ""
echo "Then run the generated TX command."
echo ""
echo "You should see: [IntercomBounty] Bounty claimed: bounty_1"
echo ""
read -p "Press Enter after claiming..."

echo ""
echo "============================================"
echo "STEP 4: Verify Claim (Both Terminals)"
echo "============================================"
echo ""
echo "Run this command in BOTH terminals:"
echo ""
echo '/tx --command "stats"'
echo ""
echo "Both should show: open: 0, claimed: 1"
echo ""
read -p "Press Enter after verifying..."

echo ""
echo "============================================"
echo "STEP 5: Submit Work (Terminal 2)"
echo "============================================"
echo ""
echo "Worker completes the work and submits proof."
echo "Copy and paste in Terminal 2 (Worker):"
echo ""
echo '/bounty_submit --id "bounty_1" --proof "https://github.com/worker-demo/calculator-app"'
echo ""
echo "Then run the generated TX command."
echo ""
echo "You should see: [IntercomBounty] Work submitted: bounty_1"
echo ""
read -p "Press Enter after submitting..."

echo ""
echo "============================================"
echo "STEP 6: Review Submission (Terminal 1)"
echo "============================================"
echo ""
echo "Poster reviews the submitted work."
echo "Copy and paste in Terminal 1 (Poster):"
echo ""
echo '/tx --command "list_bounties"'
echo ""
echo "You should see bounty_1 with status 'submitted'"
echo ""
read -p "Press Enter after reviewing..."

echo ""
echo "============================================"
echo "STEP 7: Approve Work (Terminal 1)"
echo "============================================"
echo ""
echo "Poster approves the work and releases payment."
echo "Copy and paste in Terminal 1 (Poster):"
echo ""
echo '/bounty_approve --id "bounty_1"'
echo ""
echo "Then run the generated TX command."
echo ""
echo "You should see:"
echo "  [IntercomBounty] Bounty approved: bounty_1"
echo "  Payment released: 5000000000000000000 TNK to [worker address]"
echo "  *** In production, MSB transfer would execute here ***"
echo ""
read -p "Press Enter after approving..."

echo ""
echo "============================================"
echo "STEP 8: Verify Completion (Both Terminals)"
echo "============================================"
echo ""
echo "Run this command in BOTH terminals:"
echo ""
echo '/tx --command "stats"'
echo ""
echo "Both should show: completed: 1"
echo ""
echo "Also run:"
echo ""
echo '/tx --command "list_bounties"'
echo ""
echo "bounty_1 should show status 'completed'"
echo ""
read -p "Press Enter to finish..."

echo ""
echo "============================================"
echo "  Demo Complete! ✅"
echo "============================================"
echo ""
echo "Summary of what we demonstrated:"
echo "✅ Posted a bounty with 5 TNK reward"
echo "✅ Worker claimed the bounty"
echo "✅ Worker submitted proof of work"
echo "✅ Poster approved and released payment"
echo "✅ State replicated across all peers"
echo ""
echo "Next steps:"
echo "- Try the rejection workflow (demo-reject.sh)"
echo "- Test error handling (demo-errors.sh)"
echo "- Integrate with agents via SC-Bridge"
echo ""
echo "For full testing suite, see TESTING.md"
echo ""
